site_name: ECE196 Documentation
repo_url: https://github.com/ucsd-ece196/ucsd-ece196.github.io
repo_name: ucsd-ece196.github.io
edit_uri: ""
nav:
    - Home: index.md
    - Rapid Prototyping:
      - Laser Cutting: lasercut.md
      - 3D Printing: lasercut.md
    - Python: 
      - Installation and Introduction: pythoninstall.md
      - Syntax Basics: python.md
      - List, Loops and Functions: python2.md
      - More Advanced: python3.md
    - Serial UART: serial.md
    - Raspberry Pi: rpi.md
    - OpenCV: opencv.md
    - Web Development:
      - IOT Intro: iot-project.md
      - Firebase: firebase.md
      - VueJS: web.md
      - Bootstrap: bootstrap.md
      - Security: secure.md
    - Git/Github ↗️: https://www.mrswirlyeyes.com/tutorials/introduction_to_git_github
theme:
    name: material
      
    features:
      - navigation.expand
    icon:
      repo: fontawesome/brands/github
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://www.github.com/curtisrlee
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/curtisrlee
        - icon: fontawesome/brands/facebook
          link: https://www.facebook.com/curtisrlee98