site_name: ECE196 Documentation
repo_url: https://github.com/ucsd-ece196/ucsd-ece196.github.io
repo_name: ucsd-ece196.github.io
edit_uri: ""
nav:
    - Home: index.md
    - Serial UART: serial.md
    - Python: python.md
    - Raspberry Pi: rpi.md
    - OpenCV: opencv.md
    - Webdev 1 - IOT Intro: iot-project.md
    - Webdev 2 - Firebase: firebase.md
    - Webdev 3 - VueJS: web.md
    - Webdev 4 - Bootstrap: bootstrap.md
    - Webdev 5 - Security: secure.md
    - Git/Github ↗️: https://www.mrswirlyeyes.com/tutorials/introduction_to_git_github
theme:
    name: material
    icon:
      repo: fontawesome/brands/github
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://www.github.com/curtisrlee
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/curtisrlee
        - icon: fontawesome/brands/facebook
          link: https://www.facebook.com/curtisrlee98